/**
 * Copyright (C) 2005-2013 Alfresco Software Limited.
 *
 * This file is part of Alfresco
 *
 * Alfresco is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Alfresco is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Alfresco. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @module alfresco/forms/controls/DocumentPicker
 * @extends module:alfresco/forms/controls/BaseFormControl
 * @mixes module:alfresco/core/CoreWidgetProcessing
 * @author Dave Draper
 */
define(["alfresco/forms/controls/BaseFormControl",
        "alfresco/core/CoreWidgetProcessing",
        "dojo/_base/declare",
        "dojo/_base/lang"], 
        function(BaseFormControl, CoreWidgetProcessing, declare, lang) {
   
   return declare([BaseFormControl, CoreWidgetProcessing], {
      
      /**
       * @instance
       */
      getWidgetConfig: function alfresco_forms_controls_DocumentPicker__getWidgetConfig() {
         // Return the configuration for the widget
         return {
            id : this.id + "_CONTROL",
            name: this.name,
            value: (this.value != null) ? this.value : null,
            options: (this.options != null) ? this.options : []
         };
      },
      
      /**
       * @instance
       */
      createFormControl: function alfresco_forms_controls_DocumentPicker__createFormControl(config, domNode) {
         this.alfSubscribe("ALF_ITEMS_SELECTED", lang.hitch(this, this.onItemsSelected));
         this.setModelPickerWidgetValue([]);
         return this.processWidgets(this.widgetsForControl, this.domNode);
      },

      /**
       * The value returned is the value of the [PickedItems]{@link module:alfresco/pickers/PickedItems} widget. 
       * @instance
       * @returns {object}
       */
      getValue: function alfresco_forms_controls_DocumentPicker__getValue() {
         return lang.getObject("widgetsForControl.0.config.widgets.1.config.widgets.0.config.value", false, this);
      },
      
      /**
       * Calls the [setModelPickerWidgetValue]{@link module:alfresco/forms/controls/DocumentPicker#setModelPickerWidgetValue}
       * function.
       *
       * @instance
       * @param {object} value
       */
      setValue: function alfresco_forms_controls_DocumentPicker__setValue(value) {
         this.setModelPickerWidgetValue(value);
      },

      /**
       * Updates the model to set a value of the currently selected items. It is necessary to do this because
       * the model cannot contain variable information (at least none that can be defined when the widget is
       * instantiated) so it is necessary to perform this before the [processWidgets]{@link module:alfresco/core/Core#processWidgets}
       * function is called.
       *
       * @instance
       * @param {object} value The value to set
       */
      setModelPickerWidgetValue: function alfresco_forms_controls_DocumentPicker__setModelPickerWidgetValue(value) {
         lang.setObject("widgetsForControl.0.config.widgets.1.config.widgets.0.config.value", value ,this);
      },

      /**
       * When items are picked it is necessary to update the [AlfFormDialogButton]{@link module:alfresco/buttons/AlfFormDialogButton} 
       * that generates the [form]{@link module:alfresco/forms/Form} containing the [Picker]{@link module:alfresco/pickers/Picker} because
       * the [AlfDialogService]{@link module:alfresco/dialogs/AlfDialogService} will destroy the dialog when it is closed. 
       *
       * @instance
       * @param {object} value The items to set.
       */
      updateFormDialogButton: function alfresco_forms_controls_DocumentPicker__updateFormDialogButton(value) {
         var button = lang.getObject("verticalWidgets.formDialogButton", false, this);
         if (button != null)
         {
            lang.setObject("publishPayload.widgetsContent.0.config.value", value, button);
         }
         else
         {
            this.alfLog("warn", "The button to request a form does not exist", this);
         }
      },

      /**
       * This is the dot-notation property address where to find the picked items from the dialog that was displayed.
       * It can be overridden as necessary.
       *
       * @instance
       * @type {string}
       * @default "payload.dialogContent.0.pickedItemsWidget.currentData.items"
       */
      dialogPickedItemsProperty: "dialogContent.0.pickedItemsWidget.currentData.items",

      /**
       * This is called when the [form]{@link module:alfresco/forms/Form} generated by the [AlfFormDialogButton]{@link module:alfresco/buttons/AlfFormDialogButton}
       * is submitted. The payload will contain the picked items captured by the [Picker]{@link module:alfresco/pickers/Picker}
       * widget. The items should then be rendered in the local [PickedItems]{@link module:alfresco/pickers/PickedItems} widget.
       *
       * @instance
       * @param {object} payload The details of the selected items
       */
      onItemsSelected: function alfresco_forms_controls_DocumentPicker__onItemsSelected(payload) {
         var pickedItemsWidget = this.getPickedItemsWidget();
         if (pickedItemsWidget != null && payload != null)
         {
            // Check if a "pickedItems" attribute was provided in the payload. This would be provided
            // when using the remove or remove all buttons in the main picker...
            var pickedItems = payload.pickedItems;
            if (pickedItems == null)
            {
               // ...if a "pickedItems" attribute was not provided then attempt to get the picked items
               // directly from the dialog.
               pickedItems = lang.getObject(this.dialogPickedItemsProperty, false, payload);
            }
            if (pickedItems != null)
            {
               pickedItemsWidget.currentData.items = pickedItems;
               pickedItemsWidget.renderView(false);
               this.updateFormDialogButton(pickedItems);
            }
            else
            {
               this.alfLog("warn", "No items provided to assign to PickedItems widget, nothing will be set", payload, this);
            }
         }
         else
         {
            this.alfLog("warn", "PickedItems widget is not created, it is not possible to set items", this);
         }
      },

      /**
       * Retrieves the [PickedItems widget]{@link module:alfresco/pickers/PickedItems} defined in the 
       * [widgetsForControl]{@link module:alfresco/forms/controls/DocumentPicker#widgetsForControl} model.
       * This is defined in a separate function to support functions that override the model and need to
       * obtain the widget by a different means.
       *
       * @instance
       * @returns {object} The [PickedItems widget]{@link module:alfresco/pickers/PickedItems}
       */
      getPickedItemsWidget: function alfresco_forms_controls_DocumentPicker__getPickedItemsWidget() {
         var widget = lang.getObject("verticalWidgets.pickedItemsWidget", false, this);
         return widget;
      },

      /**
       * 
       * @instance
       * @type {object}
       * @default
       */
      widgetsForControl: [
         {
            name: "alfresco/layout/VerticalWidgets",
            assignTo: "verticalWidgets",
            config: {
               widgets: [
                  {
                     name: "alfresco/pickers/PickedItems",
                     assignTo: "pickedItemsWidget"
                  },
                  {
                     name: "alfresco/buttons/AlfButton",
                     assignTo: "formDialogButton",
                     config: {
                        label: "Add",
                        publishTopic: "ALF_CREATE_DIALOG_REQUEST",
                        publishPayload: {
                           dialogTitle: "Select...",
                           handleOverflow: false,
                           widgetsContent: [
                              {
                                 name: "alfresco/pickers/Picker"
                              }
                           ],
                           widgetsButtons: [
                              {
                                 name: "alfresco/buttons/AlfButton",
                                 config: {
                                    label: "OK",
                                    publishTopic: "ALF_ITEMS_SELECTED"
                                 }
                              },
                              {
                                 name: "alfresco/buttons/AlfButton",
                                 config: {
                                    label: "Cancel",
                                    publishTopic: "NO_OP"
                                 }
                              }
                           ]
                        }
                     }
                  },
                  {
                     name: "alfresco/buttons/AlfButton",
                     config: {
                        label: "Remove All",
                        additionalCssClasses: "cancelButton",
                        publishTopic: "ALF_ITEMS_SELECTED",
                        publishPayload: {
                           pickedItems: []
                        }
                     }
                  }
               ]
            }
         }
      ]
   });
});